name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Wagner3UB
          template: classic
          # Aqui definimos para ignorar seus repos pessoais e focar nas orgs
          base: header, community
          repositories_affiliations: owner, collaborator, organization_member
          
          # Foco em Linguagens (incluindo o que você faz no Plone)
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes # Isso faz ele vasculhar commits em outras orgs
          
          # Filtro de Organizações
          # Isso garante que ele dê destaque para o Plone
          plugin_projects: yes
          plugin_projects_limit: 4
          
          # Se quiser mostrar contribuições específicas nessas orgs:
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_filter: Plone, italia # Filtra para Plone e repositórios da Itália
          
          # Remove aquele erro do "Habits" e foca no calendário 3D
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          config_timezone: Europe/Rome
          plugin_topics_mode: icons # ou labels
